# -*- coding: utf-8 -*-
"""volume_forecasting.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/131Vtu894WPZWynkJcbD6Xnkl-mq5T6D2
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from datetime import datetime, timedelta

# Generate hourly timestamps for 1 year
date_range = pd.date_range(
    start='2025-01-01',
    end='2025-12-31 23:00:00',
    freq='H'
)

df = pd.DataFrame({'timestamp': date_range})

print(df.shape)
df.head()

df['hour'] = df['timestamp'].dt.hour
df['day_of_week'] = df['timestamp'].dt.dayofweek   # Monday=0
df['month'] = df['timestamp'].dt.month
df['day'] = df['timestamp'].dt.day

df['is_weekend'] = df['day_of_week'].isin([5, 6]).astype(int)



holidays = [
    '2025-01-01',
    '2025-08-15',
    '2025-10-02',
    '2025-12-25'
]

df['is_holiday'] = df['timestamp'].dt.date.astype(str).isin(holidays).astype(int)

df.head()

voice_hour_pattern = (
    20
    + 15 * np.sin((df['hour'] - 8) * np.pi / 12)
    + 10 * np.sin((df['hour'] - 15) * np.pi / 6)
)

chat_hour_pattern = (
    15
    + 12 * np.sin((df['hour'] - 11) * np.pi / 12)
)

email_hour_pattern = (
    10
    + 8 * ((df['hour'] >= 9) & (df['hour'] <= 18)).astype(int)
)

ticket_hour_pattern = (
    8
    + 5 * ((df['hour'] >= 8) & (df['hour'] <= 20)).astype(int)
)

weekday_multiplier = np.where(df['is_weekend'] == 1, 0.7, 1.0)

# Monday spike
weekday_multiplier += np.where(df['day_of_week'] == 0, 0.2, 0)

df['marketing_campaign'] = 0

campaign_indices = np.random.choice(len(df), size=15, replace=False)

for idx in campaign_indices:
    df.loc[idx:idx+24, 'marketing_campaign'] = 1

df['outage_flag'] = 0

outage_indices = np.random.choice(len(df), size=8, replace=False)

for idx in outage_indices:
    df.loc[idx:idx+6, 'outage_flag'] = 1

df['voice_calls'] = (
    voice_hour_pattern * weekday_multiplier
    * (1 - 0.3 * df['is_holiday'])
    + 25 * df['outage_flag']
    + 8 * df['marketing_campaign'].shift(2).fillna(0)
    + np.random.normal(0, 5, len(df))
).clip(lower=0).astype(int)

df['chats'] = (
    chat_hour_pattern * weekday_multiplier
    * (1 - 0.2 * df['is_holiday'])
    + 20 * df['marketing_campaign']
    + 18 * df['outage_flag']
    + np.random.normal(0, 4, len(df))
).clip(lower=0).astype(int)

df['emails'] = (
    email_hour_pattern * weekday_multiplier
    * (1 - 0.4 * df['is_holiday'])
    + 5 * df['marketing_campaign']
    + np.random.normal(0, 3, len(df))
).clip(lower=0).astype(int)

df['tickets'] = (
    ticket_hour_pattern * weekday_multiplier
    * (1 - 0.2 * df['is_holiday'])
    + 10 * df['outage_flag']
    + np.random.normal(0, 2, len(df))
).clip(lower=0).astype(int)

df['avg_handle_time'] = (
    6
    + 2 * df['outage_flag']
    + np.random.normal(0, 0.5, len(df))
).round(2)

df['sla_breach'] = (
    (df['voice_calls'] > df['voice_calls'].quantile(0.90))
    | (df['outage_flag'] == 1)
).astype(int)

df.to_csv('volume_forecasting.csv', index=False)

